### ISSUE TITLE
tekinico_accounting_account does not exist

### ISSUE THREAD

**Issue by samrose** [nicoraynaud/odoo-personal-finances#1]
On install of this module, I get the following error:

```
openerp.service.db: CREATE DATABASE failed:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/db.py", line 42, in _initialize_db
    db_name, demo, None, update_module=True)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/loading.py", line 157, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 290, in init_module_models
    obj.init(cr)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/odoo-personal-finances/tekinico_accounting_balance.py", line 38, in init
    """)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "tekinico_accounting_account" does not exist
LINE 14:                             tekinico_accounting_account taa ...
```

**Comment by nicoraynaud** [comment]
Sorry to answer that late .

i have fixed that bug : this was due to a precedence issue in the init script imports.

it is working now.
